name: flutter_application_1
description: "Remake de Space Impact con temática de Paraguay Paralelo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del Logo usando la ruta de tu captura
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Carpetas de recursos para el motor Flame
  assets:
    - assets/images/